
23/08/20 19:07 - lib.author_ident:INFO:Create new classifier with the catalog 'a'...

23/08/20 19:09 - lib.author_ident:INFO:Load existing classifier with the catalog 'a'...

23/08/20 21:27 - lib.author_ident:INFO:Load existing classifier with the catalog 'gutenbergident.txt'...

23/08/20 21:34 - lib.author_ident:INFO:Create new classifier with the catalog 'gutenbergident.txt'...

23/08/20 21:53 - lib.author_ident:INFO:Load existing classifier with the catalog 'gutenbergident.txt'...

23/08/20 21:54 - lib.author_ident:INFO:Load existing classifier with the catalog 'gutenbergident.txt'...

23/08/20 21:54 - lib.author_ident:ERROR:Calling forget(<lib.author_ident.AuthorIdent object at 0x1744EF50>, 'a')...
Traceback (most recent call last):
  File "D:\GitHub\lib\errors.py", line 40, in wrapper
    value = func(*args, **kwargs)
  File "D:\GitHub\lib\author_ident.py", line 106, in forget
    raise CatalogError(f"No entry for '{author}' exists.")
lib.errors.CatalogError: No entry for 'a' exists.
